### ISSUE TITLE
Content-Length header not updated when response body is edited

### ISSUE THREAD

**Issue by f-che** [Lemick/hoverfly-ui#17]
When the response body is changed from within the editor field, the `Content-Length` response header (if present) is not adjusted accordingly.

This leads Hoverfly to raise this kind of error when importing back the edited simulation :
> WARNING: Response contains incorrect Content-Length header on data.pairs[0].response, please correct or remove header

Could the plugin compute/update this header if needed (or at worst, remove it when the resp body is changed) ?
    
    
BTW thank you for this nice plugin Mickaël !  :)

**Comment by Lemick** [comment]
Hello, thanks for the suggestion, I will take a look at it  😄

**Comment by Lemick** [comment]
@f-che Could you please tell me if it fit your use case by testing on[ this branch](https://lemick.github.io/hoverfly-ui/pr-preview/pr-20/) ?

**Comment by fchevassu** [comment]
It works like a charm, thank you! 👍 
_(sorry for the late reply, I was on vacation)_

**Comment by f-che** [comment]
It works like a charm, thank you! 👍
(sorry for the late reply, I was on vacation)
